# Generated by Django 5.0.6 on 2024-09-03 19:55

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tcore', '0003_about_alter_contact_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='İçerik'),
        ),
    ]
