# Generated by Django 5.0.6 on 2024-09-13 13:11

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcore', '0005_about_content_en_about_content_tr_about_title_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Hizmet Adı')),
                ('title_tr', models.CharField(max_length=200, null=True, verbose_name='Hizmet Adı')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Hizmet Adı')),
                ('content', ckeditor.fields.RichTextField(verbose_name='İçerik')),
                ('content_tr', ckeditor.fields.RichTextField(null=True, verbose_name='İçerik')),
                ('content_en', ckeditor.fields.RichTextField(null=True, verbose_name='İçerik')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=200)),
            ],
            options={
                'verbose_name': 'Hizmetlerim',
                'verbose_name_plural': 'Hizmetlerim',
            },
        ),
    ]
