# Generated by Django 5.0.6 on 2024-09-15 17:46

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcore', '0007_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategori Adı')),
                ('name_tr', models.CharField(max_length=100, null=True, verbose_name='Kategori Adı')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Kategori Adı')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('title_tr', models.CharField(max_length=200, null=True, verbose_name='Başlık')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Başlık')),
                ('image', models.ImageField(upload_to='blog/', verbose_name='Resim')),
                ('content', ckeditor.fields.RichTextField(verbose_name='İçerik')),
                ('content_tr', ckeditor.fields.RichTextField(null=True, verbose_name='İçerik')),
                ('content_en', ckeditor.fields.RichTextField(null=True, verbose_name='İçerik')),
                ('views', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='GÜncelleme Tarihi')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=200, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tcore.category')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blog',
            },
        ),
    ]
