# Generated by Django 5.0.6 on 2024-09-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcore', '0008_category_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_1', models.ImageField(null=True, upload_to='dimg/', verbose_name='Logo')),
                ('logo_2', models.ImageField(null=True, upload_to='dimg/', verbose_name='Logo')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('title_tr', models.CharField(max_length=200, null=True, verbose_name='Başlık')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Başlık')),
                ('dest', models.TextField(verbose_name='Açıklama')),
                ('dest_tr', models.TextField(null=True, verbose_name='Açıklama')),
                ('dest_en', models.TextField(null=True, verbose_name='Açıklama')),
                ('keywords', models.CharField(max_length=255, verbose_name='Anahtar Kelimeler')),
                ('keywords_tr', models.CharField(max_length=255, null=True, verbose_name='Anahtar Kelimeler')),
                ('keywords_en', models.CharField(max_length=255, null=True, verbose_name='Anahtar Kelimeler')),
                ('phone', models.CharField(max_length=15, verbose_name='Telefon Numarası')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Adresi')),
                ('city', models.CharField(max_length=50, verbose_name='İl')),
                ('district', models.CharField(max_length=200, verbose_name='İlçe')),
                ('address', models.TextField(verbose_name='Adres')),
                ('facebook', models.URLField(verbose_name='Facebook')),
                ('twitter', models.URLField(verbose_name='Twitter')),
                ('instagram', models.URLField(verbose_name='Instagram')),
                ('linkedin', models.URLField(verbose_name='Linkedin')),
                ('youtube', models.URLField(verbose_name='Youtube')),
            ],
            options={
                'verbose_name': 'Ayarlar',
                'verbose_name_plural': 'Ayarlar',
            },
        ),
    ]
